config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new_task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>UPDATE A TASK</h1>
<%= form_with model: @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.check_box :completed %>
  <%= t.label :completed %>
  <%= t.submit %>
<% end %>

<%= link_to "See all tasks",
    tasks_path(@task)%>

app/views/tasks/index.html.erb
<h1>ALL THE TASKS</h1>

<ul>
  <% @tasks.each do |t| %>
    <li><%= link_to t.title, task_path(t) %><%= link_to "🗑", task_path(t),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%></li>
  <% end %>
</ul>

<%= link_to "Create a task", new_task_path(@task)%>

app/views/tasks/new.html.erb
<h1>ADD A NEW TASK</h1>
<%= form_with model: @task do |t| %>
  <%= t.label :title %>
  <%= t.text_field :title %>
  <%= t.label :details %>
  <%= t.text_field :details %>
  <%= t.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>

<li>
  <ul><%= @task.details %></ul>
  <ul>COMPLETED : <%if @task.completed %>
    <%="YES"%> 
    <%else%> 
    <%="NO"%>
    <%end%></ul>
</li>

<%= link_to "Edit",
    edit_task_path(@task)%>

<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>
<%= link_to "See all tasks",
    tasks_path(@task)%> 